name: Deploy to Cloud Run
on:
  push:
    branches:
      - master
      - dev

env:
  SERVICE_NAME: backend
  ENV_MODE: prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Assign ENV_MODE
        if: github.ref_name != 'master'
        run: |
          echo "ENV_MODE=dev" >> $GITHUB_ENV
      - name: Change SERVICE_NAME
        run: |
          echo "SERVICE_NAME=$SERVICE_NAME-$ENV_MODE" >> $GITHUB_ENV
      - name: Create variables
        id: vars
        run: |
          echo "::set-output name=FIREBASE_CRED::FIREBASE_CRED_$ENV_MODE"
          echo "::set-output name=GCPSA_CRED::GCPSA_CRED_$ENV_MODE"
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create dir
        run: |
          mkdir -p firebase
      - name: Create firebase json
        id: cred-firebase
        uses: jsdaniell/create-json@1.1.2
        with:
          name: firebase_config_${{ env.ENV_MODE }}.json
          json: ${{ secrets[steps.vars.outputs.FIREBASE_CRED] }}
          dir: 'firebase/'
      - name: Create gcp json
        id: cred-gcp
        uses: jsdaniell/create-json@1.1.2
        with:
          name: service_account_${{ env.ENV_MODE }}.json
          json: ${{ secrets[steps.vars.outputs.GCPSA_CRED] }}
          dir: 'firebase/'
      - name: Deploy to Cloud Run
        env:
          CI: false
          PROJECT_ID: moondream-reality
        uses: google-github-actions/deploy-cloudrun@v0.6.0
        with:
          service: ${{ env.SERVICE_NAME }}
          source: .
          region: asia-east1
          credentials: ${{ secrets.MOONDREAM_DEV_GCP_SA_KEY }}
          env_vars: ENV_MODE=${{ env.ENV_MODE }}
